defmodule ViaUtils.Shared.ValueNames do
  defmacro accel_x_mpss, do: :accel_x_mpss
  defmacro accel_y_mpss, do: :accel_y_mpss
  defmacro accel_z_mpss, do: :accel_z_mpss
  defmacro agl_m, do: :agl_m
  defmacro airspeed_mps, do: :airspeed_mps
  defmacro altitude_m, do: :altitude_m
  defmacro attitude_rad, do: :attitude_rad
  defmacro attrate_rps, do: :attrate_rps
  defmacro bodyrate_x_rps, do: :bodyrate_x_rps
  defmacro bodyrate_y_rps, do: :bodyrate_y_rps
  defmacro bodyrate_z_rps, do: :bodyrate_z_rps
  defmacro course_rad, do: :course_rad
  defmacro downward_range_distance_m, do: :downward_range_distance_m
  defmacro dt_s, do: :dt_s
  defmacro ground_altitude_m, do: :ground_altitude_m
  defmacro groundspeed_mps, do: :groundspeed_mps
  defmacro gyro_x_rps, do: :gyro_x_rps
  defmacro gyro_y_rps, do: :gyro_y_rps
  defmacro gyro_z_rps, do: :gyro_z_rps
  defmacro itow_s, do: :itow_s
  defmacro latitude_rad, do: :latitude_rad
  defmacro longitude_rad, do: :longitude_rad
  defmacro pilot_control_level, do: :pilot_control_level
  defmacro pitch_rad, do: :pitch_rad
  defmacro pitchrate_rps, do: :pitchrate_rps
  defmacro position_rrm, do: :position_rrm
  defmacro quat_w, do: :quat_w
  defmacro quat_x, do: :quat_x
  defmacro quat_y, do: :quat_y
  defmacro quat_z, do: :quat_z
  defmacro roll_rad, do: :roll_rad
  defmacro rollrate_rps, do: :rollrate_rps
  defmacro time_since_boot_s, do: :time_since_boot_s
  defmacro velocity_mps, do: :velocity_mps
  defmacro v_north_mps, do: :v_north_mps
  defmacro v_east_mps, do: :v_east_mps
  defmacro v_down_mps, do: :v_down_mps
  defmacro vertical_velocity_mps, do: :vertical_velocity_mps
  defmacro yaw_rad, do: :yaw_rad
  defmacro yawrate_rps, do: :yawrate_rps
end
